site_name: PFS Target Database
site_url: https://pfs-etc.naoj.hawaii.edu/targetdb/
site_author: Masato Onodera

copyright: Copyright &copy; <a href="https://subarutelescope.org">Subaru Telescope</a>, <a href="https://www.nao.ac.jp">NAOJ</a>

repo_url: https://github.com/Subaru-PFS/ets_target_database/
repo_name: Subaru-PFS/ets_target_database

# use_directory_urls: false

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Data Schema:
    - schema/index.md
    - filter_name: schema/filter_name.md
    - fluxstd: schema/fluxstd.md
    - input_catalog: schema/input_catalog.md
    - pfs_arm: schema/pfs_arm.md
    - proposal: schema/proposal.md
    - proposal_category: schema/proposal_category.md
    - sky: schema/sky.md
    - target: schema/target.md
    - target_type: schema/target_type.md
    - user_pointing: schema/user_pointing.md
  - Reference:
    - CLI Reference: reference/cli.md
    - API Reference: reference/api.md
  - Examples:
    - examples/index.md
    - Operating targetdb: examples/operation.md
    - Preparing Input Data: examples/preparation.md
    - Useful Queries: examples/queries.md
    - Docker Tutorial: examples/docker.md
    - Obsproc Tutorial: examples/obsproc.md
  - Contact: contact.md
  - tbls:
    - tbls/README.md
    - tbls/public.filter_name.md
    - tbls/public.fluxstd.md
    - tbls/public.input_catalog.md
    - tbls/public.pfs_arm.md
    - tbls/public.proposal.md
    - tbls/public.proposal_category.md
    - tbls/public.sky.md
    - tbls/public.target.md
    - tbls/public.target_type.md
    - tbls/public.user_pointing.md

plugins:
  - search
  - social
  - privacy

theme:
  name: material
  palette:
    primary: blue grey
    accent: indigo
  icon:
    logo: material/database
    repo: fontawesome/brands/github
  font:
    text: Lato
    # code: Intel One Mono
    # text: Lato
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    # - navigation.sections
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - tables
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - toc:
       permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Subaru-PFS/ets_target_database/
      name: Subaru-PFS/ets_target_database on GitHub