[project]
name = "targetdb"
# version = "0.1.0"
dynamic = ["version"]
description = "PFS target database (targetDB) tools"
authors = [{ name = "Masato Onodera", email = "monodera@naoj.org" }]
dependencies = [
    "setuptools",
    "loguru",
    "pandas",
    "sqlalchemy",
    "tabulate",
    "toml",
    "numpy",
    "alembic",
    "psycopg2",
    "sqlalchemy-utils",
    "wheel",
    "ipython",
]
requires-python = ">=3.8, <4"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Database",
    "Topic :: Scientific/Engineering :: Astronomy",
]

[project.urls]
homepage = "https://github.com/Subaru-PFS/ets_target_database"
source = "https://github.com/Subaru-PFS/ets_target_database"

[project.scripts]
pfs_targetdb_create_database = "targetdb.cli.pfs_targetdb_database_helpers:main_create_database"
pfs_targetdb_create_schema = "targetdb.cli.pfs_targetdb_create_schema:main"
pfs_targetdb_draw_diagram = "targetdb.cli.pfs_targetdb_draw_diagram:main"
pfs_targetdb_drop_database = "targetdb.cli.pfs_targetdb_database_helpers:main_drop_database"
pfs_targetdb_generate_mdtable = "targetdb.cli.pfs_targetdb_generate_mdtable:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "targetdb.__version__" }
