[targetdb]
host = "hostname"
port = 5432
dbname = "dbname"
user = "username"
password = "password"
dialect = "postgresql"

[gaiadb]
host = "hostname"
port = 5432
dbname = "dbname"
user = "username"
password = "password"

[schemacrawler]
SCHEMACRAWLERDIR = "../../../schemacrawler-16.15.7-distribution/"

[netflow]
use_gurobi = true

[gurobi]
seed = 0
presolve = 1
method = 0
degenmoves = 0
heuristics = 0.6
mipfocus = 0
mipgap = 5.0e-2
PreSOS2Encoding = 0
PreSOS1Encoding = 0