version: '3'

services:
  db:
    image: postgres:10.6
    # restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: targetDB
    volumes:
      - ./db-data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
