"""Add columns for photometric errors in the fluxstd table

Revision ID: c4e16db3e7e1
Revises: a63ff2b68f44
Create Date: 2022-10-20 17:45:27.991776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e16db3e7e1'
down_revision = 'a63ff2b68f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fluxstd', sa.Column('psf_mag_error_g', sa.Float(), nullable=True, comment='Error in g-band PSF magnitude (AB mag)'))
    op.add_column('fluxstd', sa.Column('psf_mag_error_r', sa.Float(), nullable=True, comment='Error in r-band PSF magnitude (AB mag)'))
    op.add_column('fluxstd', sa.Column('psf_mag_error_i', sa.Float(), nullable=True, comment='Error in i-band PSF magnitude (AB mag)'))
    op.add_column('fluxstd', sa.Column('psf_mag_error_z', sa.Float(), nullable=True, comment='Error in z-band PSF magnitude (AB mag)'))
    op.add_column('fluxstd', sa.Column('psf_mag_error_y', sa.Float(), nullable=True, comment='Error in y-band PSF magnitude (AB mag)'))
    op.add_column('fluxstd', sa.Column('psf_mag_error_j', sa.Float(), nullable=True, comment='Error in J band PSF magnitude (AB mag)'))
    op.add_column('fluxstd', sa.Column('psf_flux_error_g', sa.Float(), nullable=True, comment='Error in g-band PSF flux (nJy)'))
    op.add_column('fluxstd', sa.Column('psf_flux_error_r', sa.Float(), nullable=True, comment='Error in r-band PSF flux (nJy)'))
    op.add_column('fluxstd', sa.Column('psf_flux_error_i', sa.Float(), nullable=True, comment='Error in i-band PSF flux (nJy)'))
    op.add_column('fluxstd', sa.Column('psf_flux_error_z', sa.Float(), nullable=True, comment='Error in z-band PSF flux (nJy)'))
    op.add_column('fluxstd', sa.Column('psf_flux_error_y', sa.Float(), nullable=True, comment='Error in y-band PSF flux (nJy)'))
    op.add_column('fluxstd', sa.Column('psf_flux_error_j', sa.Float(), nullable=True, comment='Error in J band PSF flux (nJy)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fluxstd', 'psf_flux_error_j')
    op.drop_column('fluxstd', 'psf_flux_error_y')
    op.drop_column('fluxstd', 'psf_flux_error_z')
    op.drop_column('fluxstd', 'psf_flux_error_i')
    op.drop_column('fluxstd', 'psf_flux_error_r')
    op.drop_column('fluxstd', 'psf_flux_error_g')
    op.drop_column('fluxstd', 'psf_mag_error_j')
    op.drop_column('fluxstd', 'psf_mag_error_y')
    op.drop_column('fluxstd', 'psf_mag_error_z')
    op.drop_column('fluxstd', 'psf_mag_error_i')
    op.drop_column('fluxstd', 'psf_mag_error_r')
    op.drop_column('fluxstd', 'psf_mag_error_g')
    # ### end Alembic commands ###
