"""Add ob_code in target table.

Revision ID: 85c7fd1caf42
Revises: 92d3534d8bf8
Create Date: 2022-12-06 14:26:11.366386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c7fd1caf42'
down_revision = '92d3534d8bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('ob_code', sa.String(), nullable=True, comment='Identifer for a combination of a target, observing mode, and exposure time in a program.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'ob_code')
    # ### end Alembic commands ###
