"""New table, filter_name, is created.

Revision ID: db972b098339
Revises: 9ef97473b712
Create Date: 2022-12-06 19:30:37.646535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db972b098339'
down_revision = '9ef97473b712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_name',
    sa.Column('filter_name', sa.String(), autoincrement=False, nullable=False, comment='Filter name (e.g., g_ps1)'),
    sa.Column('filter_name_description', sa.String(), nullable=True, comment='Descriptino of the filter'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation time [YYYY-MM-DDThh:mm:ss] (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Update time [YYYY-MM-DDThh:mm:ss] (UTC)'),
    sa.PrimaryKeyConstraint('filter_name'),
    sa.UniqueConstraint('filter_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter_name')
    # ### end Alembic commands ###
