"""Add error columns for psf_{mag,flux} in the target table

Revision ID: 92d3534d8bf8
Revises: c4e16db3e7e1
Create Date: 2022-11-11 13:55:46.817819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d3534d8bf8'
down_revision = 'c4e16db3e7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('psf_mag_error_g', sa.Float(), nullable=True, comment='Error in g-band PSF magnitude (AB mag)'))
    op.add_column('target', sa.Column('psf_mag_error_r', sa.Float(), nullable=True, comment='Error in r-band PSF magnitude (AB mag)'))
    op.add_column('target', sa.Column('psf_mag_error_i', sa.Float(), nullable=True, comment='Error in i-band PSF magnitude (AB mag)'))
    op.add_column('target', sa.Column('psf_mag_error_z', sa.Float(), nullable=True, comment='Error in z-band PSF magnitude (AB mag)'))
    op.add_column('target', sa.Column('psf_mag_error_y', sa.Float(), nullable=True, comment='Error in y-band PSF magnitude (AB mag)'))
    op.add_column('target', sa.Column('psf_mag_error_j', sa.Float(), nullable=True, comment='Error in J band PSF magnitude (AB mag)'))
    op.add_column('target', sa.Column('psf_flux_error_g', sa.Float(), nullable=True, comment='Error in g-band PSF flux (nJy)'))
    op.add_column('target', sa.Column('psf_flux_error_r', sa.Float(), nullable=True, comment='Error in r-band PSF flux (nJy)'))
    op.add_column('target', sa.Column('psf_flux_error_i', sa.Float(), nullable=True, comment='Error in i-band PSF flux (nJy)'))
    op.add_column('target', sa.Column('psf_flux_error_z', sa.Float(), nullable=True, comment='Error in z-band PSF flux (nJy)'))
    op.add_column('target', sa.Column('psf_flux_error_y', sa.Float(), nullable=True, comment='Error in y-band PSF flux (nJy)'))
    op.add_column('target', sa.Column('psf_flux_error_j', sa.Float(), nullable=True, comment='Error in J band PSF flux (nJy)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'psf_flux_error_j')
    op.drop_column('target', 'psf_flux_error_y')
    op.drop_column('target', 'psf_flux_error_z')
    op.drop_column('target', 'psf_flux_error_i')
    op.drop_column('target', 'psf_flux_error_r')
    op.drop_column('target', 'psf_flux_error_g')
    op.drop_column('target', 'psf_mag_error_j')
    op.drop_column('target', 'psf_mag_error_y')
    op.drop_column('target', 'psf_mag_error_z')
    op.drop_column('target', 'psf_mag_error_i')
    op.drop_column('target', 'psf_mag_error_r')
    op.drop_column('target', 'psf_mag_error_g')
    # ### end Alembic commands ###
