"""Add a unique constraint by (obj_id, input_catalog_id, version) for fluxstd

Revision ID: 10e6d0a4610a
Revises: 790fae2257ac
Create Date: 2023-04-20 15:03:37.686829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e6d0a4610a'
down_revision = '790fae2257ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('fluxstd_q3c_ang2ipix_idx', table_name='fluxstd')
    op.create_unique_constraint('uq_obj_id_input_catalog_id_version', 'fluxstd', ['obj_id', 'input_catalog_id', 'version'])
    # op.drop_index('sky_q3c_ang2ipix_idx', table_name='sky')
    # op.drop_index('target_q3c_ang2ipix_idx', table_name='target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('target_q3c_ang2ipix_idx', 'target', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # op.create_index('sky_q3c_ang2ipix_idx', 'sky', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    op.drop_constraint('uq_obj_id_input_catalog_id_version', 'fluxstd', type_='unique')
    # op.create_index('fluxstd_q3c_ang2ipix_idx', 'fluxstd', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # ### end Alembic commands ###
