"""Add a unique constraint (proposal_id, ob_code) in the target table

Revision ID: 790fae2257ac
Revises: c5f125bd0b9b
Create Date: 2023-04-19 18:14:40.791644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790fae2257ac'
down_revision = 'c5f125bd0b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('fluxstd_q3c_ang2ipix_idx', table_name='fluxstd')
    # op.drop_index('sky_q3c_ang2ipix_idx', table_name='sky')
    # op.drop_index('target_q3c_ang2ipix_idx', table_name='target')
    op.create_unique_constraint('uq_proposal_id_ob_code', 'target', ['proposal_id', 'ob_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_proposal_id_ob_code', 'target', type_='unique')
    # op.create_index('target_q3c_ang2ipix_idx', 'target', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # op.create_index('sky_q3c_ang2ipix_idx', 'sky', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # op.create_index('fluxstd_q3c_ang2ipix_idx', 'fluxstd', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # ### end Alembic commands ###
