"""add queue-classical-too flags

Revision ID: f07c300ae87f
Revises: bc79254cc64b
Create Date: 2024-06-24 16:51:36.392229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07c300ae87f'
down_revision = 'bc79254cc64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_catalog', sa.Column('is_classical', sa.Boolean(), nullable=True, comment='True if the classical mode is requested'))
    op.add_column('proposal', sa.Column('is_too', sa.Boolean(), nullable=True, comment='True when the proposal is ToO'))
    op.alter_column('target', 'qa_reference_arm',
               existing_type=sa.VARCHAR(),
               comment="Reference arm to evaluate effective exposure time ('b', 'r', 'n', 'm')",
               existing_comment="Reference arm to evaluate effective exposure time ['b'|'r'|'n'|'m']",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target', 'qa_reference_arm',
               existing_type=sa.VARCHAR(),
               comment="Reference arm to evaluate effective exposure time ['b'|'r'|'n'|'m']",
               existing_comment="Reference arm to evaluate effective exposure time ('b', 'r', 'n', 'm')",
               existing_nullable=True)
    op.drop_column('proposal', 'is_too')
    op.drop_column('input_catalog', 'is_classical')
    # ### end Alembic commands ###
