"""Add allocated_time in total, lr, and mr

Revision ID: 71eba81781d9
Revises: 099e9069f2b7
Create Date: 2024-02-02 15:11:44.124658

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "71eba81781d9"
down_revision = "099e9069f2b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "proposal", "allocated_time", new_column_name="allocated_time_total"
    )
    op.add_column(
        "proposal",
        sa.Column(
            "allocated_time_lr",
            sa.Float(),
            nullable=True,
            comment="Total fiberhours for the low-resolution mode allocated by TAC (hour)",
        ),
    )
    op.add_column(
        "proposal",
        sa.Column(
            "allocated_time_mr",
            sa.Float(),
            nullable=True,
            comment="Total fiberhours for the medium-resolution mode allocated by TAC (hour)",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "proposal", "allocated_time_total", new_column_name="allocated_time"
    )
    op.drop_column("proposal", "allocated_time_mr")
    op.drop_column("proposal", "allocated_time_lr")
    # ### end Alembic commands ###
