"""add active flag to the input_catalog table

Revision ID: f8bacfde2cef
Revises: 1d0bd9825071
Create Date: 2024-05-01 17:09:26.387829

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f8bacfde2cef"
down_revision = "1d0bd9825071"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "input_catalog",
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=True,
            comment="Flag to indicate if the input catalog is active (default: True)",
        ),
    )
    op.execute(
        """
        UPDATE input_catalog
        SET active = TRUE
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("input_catalog", "active")
    # ### end Alembic commands ###
