"""Add gaia parameters in the fluxstd table

Revision ID: d024af8c52f2
Revises: 320fc1f7de3b
Create Date: 2024-04-04 17:34:37.233549

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d024af8c52f2"
down_revision = "320fc1f7de3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fluxstd",
        sa.Column(
            "teff_gspphot",
            sa.Float(),
            nullable=True,
            comment="Effective temperature inferred by GSP-phot Aeneas [K]",
        ),
    )
    op.add_column(
        "fluxstd",
        sa.Column(
            "teff_gspphot_lower",
            sa.Float(),
            nullable=True,
            comment="Lower confidence level (16%) of effective temperature inferred by GSP-phot Aeneas [K]",
        ),
    )
    op.add_column(
        "fluxstd",
        sa.Column(
            "teff_gspphot_upper",
            sa.Float(),
            nullable=True,
            comment="Upper confidence level (84%) of effective temperature inferred by GSP-phot Aeneas [K]",
        ),
    )
    op.add_column(
        "fluxstd",
        sa.Column(
            "is_fstar_gaia",
            sa.Boolean(),
            default=False,
            comment="Flag for F-star from Gaia (Teff=6000-7500K if True)",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fluxstd", "is_fstar_gaia")
    op.drop_column("fluxstd", "teff_gspphot_upper")
    op.drop_column("fluxstd", "teff_gspphot_lower")
    op.drop_column("fluxstd", "teff_gspphot")
    # ### end Alembic commands ###
