"""refine default values and nullable conditions

Revision ID: 1d0bd9825071
Revises: 0049efa2957b
Create Date: 2024-04-22 16:11:59.655450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0bd9825071'
down_revision = '0049efa2957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('input_catalog', 'input_catalog_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Name of the input catalog (e.g., Gaia DR2, HSC-SSP PDR3, etc.)')
    op.alter_column('proposal', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Group ID in STARS (e.g., o21195?)',
               autoincrement=False)
    op.alter_column('proposal', 'pi_last_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment="PI's last name")
    op.alter_column('proposal', 'rank',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='TAC score')
    op.alter_column('proposal', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='TAC grade (A/B/C/F in the case of HSC queue)')
    op.alter_column('proposal_category', 'proposal_category_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Proposal category name (e.g., Openuse, Keck, Gemini, and UH)')
    op.alter_column('target', 'effective_exptime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='Requested effective exposure time (s)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target', 'effective_exptime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='Requested effective exposure time (s)')
    op.alter_column('proposal_category', 'proposal_category_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Proposal category name (e.g., Openuse, Keck, Gemini, and UH)')
    op.alter_column('proposal', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='TAC grade (A/B/C/F in the case of HSC queue)')
    op.alter_column('proposal', 'rank',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='TAC score')
    op.alter_column('proposal', 'pi_last_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment="PI's last name")
    op.alter_column('proposal', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Group ID in STARS (e.g., o21195?)',
               autoincrement=False)
    op.alter_column('input_catalog', 'input_catalog_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Name of the input catalog (e.g., Gaia DR2, HSC-SSP PDR3, etc.)')
    # ### end Alembic commands ###
