"""add arm info

Revision ID: 63584f7b182a
Revises: 1027c2966c63
Create Date: 2024-06-06 14:51:35.709957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63584f7b182a'
down_revision = '1027c2966c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pfs_arm',
    sa.Column('name', sa.String(), nullable=False, comment="Arm name (e.g., 'b', 'r', 'n', and 'm')"),
    sa.Column('description', sa.String(), nullable=True, comment='Arm description'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True, comment='The date and time in UTC when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='The date and time in UTC when the record was last updated'),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column('target', sa.Column('qa_reference_arm', sa.String(), nullable=True, comment="Reference arm to evaluate effective exposure time ['b'|'r'|'n'|'m']"))
    op.create_foreign_key(None, 'target', 'pfs_arm', ['qa_reference_arm'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'target', type_='foreignkey')
    op.drop_column('target', 'qa_reference_arm')
    op.drop_table('pfs_arm')
    # ### end Alembic commands ###
