"""Update unique constraint for the target table

Revision ID: 065b74905fb6
Revises: 1f393a55b6d8
Create Date: 2024-04-16 10:55:45.817899

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "065b74905fb6"
down_revision = "1f393a55b6d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_proposal_id_ob_code", "target", type_="unique")
    op.create_unique_constraint(
        "uq_proposal_id_ob_code_input_catalog_id_obj_id",
        "target",
        ["proposal_id", "ob_code", "input_catalog_id", "obj_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_proposal_id_ob_code_input_catalog_id_obj_id", "target", type_="unique"
    )
    op.create_unique_constraint(
        "uq_proposal_id_ob_code", "target", ["proposal_id", "ob_code"]
    )
    # ### end Alembic commands ###
