"""pfs_arm.name to be unique

Revision ID: bc79254cc64b
Revises: 63584f7b182a
Create Date: 2024-06-06 17:22:08.628641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc79254cc64b'
down_revision = '63584f7b182a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pfs_arm', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pfs_arm', type_='unique')
    # ### end Alembic commands ###
