"""add partner column in the proposal table and partner table

Revision ID: 0b72e62efd44
Revises: b68482e38606
Create Date: 2024-12-20 14:54:09.851011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b72e62efd44'
down_revision = 'b68482e38606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('partner_id', sa.Integer(), autoincrement=False, nullable=False, comment='Unique identifier of the partner'),
    sa.Column('partner_name', sa.String(), nullable=False, comment='Name of the partner (e.g., subaru, gemini, keck, and uh)'),
    sa.Column('partner_description', sa.String(), nullable=True, comment='Description of the partner'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True, comment='The date and time in UTC when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='The date and time in UTC when the record was last updated'),
    sa.PrimaryKeyConstraint('partner_id'),
    sa.UniqueConstraint('partner_id'),
    sa.UniqueConstraint('partner_name')
    )
    op.add_column('proposal', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposal', 'partner', ['partner_id'], ['partner_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_column('proposal', 'partner_id')
    op.drop_table('partner')
    # ### end Alembic commands ###
