"""unique constraints on target

Revision ID: 368dce443754
Revises: 8f188c3cb652
Create Date: 2024-05-02 15:52:05.728826

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "368dce443754"
down_revision = "8f188c3cb652"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_proposal_id_ob_code_input_catalog_id_obj_id", "target", type_="unique"
    )
    op.create_unique_constraint(
        "target_propid_obcode_catid_objid_resolution_key",
        "target",
        [
            "proposal_id",
            "ob_code",
            "input_catalog_id",
            "obj_id",
            "is_medium_resolution",
        ],
    )
    op.create_unique_constraint(
        "target_propid_obcode_key", "target", ["proposal_id", "ob_code"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("target_propid_obcode_key", "target", type_="unique")
    op.drop_constraint(
        "target_propid_obcode_catid_objid_resolution_key", "target", type_="unique"
    )
    op.create_unique_constraint(
        "uq_proposal_id_ob_code_input_catalog_id_obj_id",
        "target",
        ["proposal_id", "ob_code", "input_catalog_id", "obj_id"],
    )
    # ### end Alembic commands ###
