"""remove unique constraint from input_catalog_name

Revision ID: 1f393a55b6d8
Revises: eeb9bd9b8d91
Create Date: 2024-04-16 10:49:50.036660

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1f393a55b6d8"
down_revision: Union[str, None] = "eeb9bd9b8d91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "input_catalog",
        "input_catalog_id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False, start=10000, maxvalue=89999, cycle=False
        ),
        comment="Unique identifier for input catalogs",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_constraint(
        "input_catalog_input_catalog_name_key", "input_catalog", type_="unique"
    )
    op.create_unique_constraint(None, "input_catalog", ["input_catalog_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "input_catalog", type_="unique")
    op.create_unique_constraint(
        "input_catalog_input_catalog_name_key", "input_catalog", ["input_catalog_name"]
    )
    op.alter_column(
        "input_catalog",
        "input_catalog_id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=89999,
            cycle=False,
            cache=1,
        ),
        comment=None,
        existing_comment="Unique identifier for input catalogs",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
