"""Fix typo in filter relationship in fluxstd

Revision ID: b010233c946e
Revises: d024af8c52f2
Create Date: 2024-04-08 09:28:14.313541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b010233c946e'
down_revision = 'd024af8c52f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
