"""test file_template format

Revision ID: f0b7483d9904
Revises: b45b1bf02a80
Create Date: 2022-05-11 22:33:41.365399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b7483d9904'
down_revision = 'b45b1bf02a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
