"""test format

Revision ID: b45b1bf02a80
Revises: a980b74a499f
Create Date: 2022-05-11 22:31:19.613893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45b1bf02a80'
down_revision = 'a980b74a499f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
