"""baseline autogenerate

Revision ID: 3e2581ddb52c
Revises: 6407841f5938
Create Date: 2022-05-11 16:48:43.166389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2581ddb52c'
down_revision = '6407841f5938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cluster', ['cluster_id', 'target_id'])
    op.create_unique_constraint(None, 'fluxstd', ['fluxstd_id'])
    op.create_unique_constraint(None, 'input_catalog', ['input_catalog_id'])
    op.create_unique_constraint(None, 'proposal', ['proposal_id'])
    op.create_unique_constraint(None, 'proposal_category', ['proposal_category_id'])
    op.create_unique_constraint(None, 'sky', ['sky_id'])
    op.create_unique_constraint(None, 'target', ['target_id'])
    op.create_unique_constraint(None, 'target_type', ['target_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'target_type', type_='unique')
    op.drop_constraint(None, 'target', type_='unique')
    op.drop_constraint(None, 'sky', type_='unique')
    op.drop_constraint(None, 'proposal_category', type_='unique')
    op.drop_constraint(None, 'proposal', type_='unique')
    op.drop_constraint(None, 'input_catalog', type_='unique')
    op.drop_constraint(None, 'fluxstd', type_='unique')
    op.drop_constraint(None, 'cluster', type_='unique')
    # ### end Alembic commands ###
