"""add filter columns in the target table

Revision ID: f26b6e6d3224
Revises: 3e2581ddb52c
Create Date: 2022-05-11 16:54:09.391335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26b6e6d3224'
down_revision = '3e2581ddb52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('filter_g', sa.String(), nullable=True, comment='g-band filter (g_hsc, g_ps1, g_sdss, etc.)'))
    op.add_column('target', sa.Column('filter_r', sa.String(), nullable=True, comment='r-band filter (r_hsc, r_ps1, r_sdss, etc.)'))
    op.add_column('target', sa.Column('filter_i', sa.String(), nullable=True, comment='i-band filter (i_hsc, i_ps1, i_sdss, etc.)'))
    op.add_column('target', sa.Column('filter_z', sa.String(), nullable=True, comment='z-band filter (z_hsc, z_ps1, z_sdss, etc.)'))
    op.add_column('target', sa.Column('filter_y', sa.String(), nullable=True, comment='y-band filter (y_hsc, y_ps1, y_sdss, etc.)'))
    op.add_column('target', sa.Column('filter_j', sa.String(), nullable=True, comment='j-band filter (j_mko, etc.)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'filter_j')
    op.drop_column('target', 'filter_y')
    op.drop_column('target', 'filter_z')
    op.drop_column('target', 'filter_i')
    op.drop_column('target', 'filter_r')
    op.drop_column('target', 'filter_g')
    # ### end Alembic commands ###
