"""Foreign key relationships to filter_name created

Revision ID: d34d4aa2914a
Revises: db972b098339
Create Date: 2022-12-06 22:13:28.300403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34d4aa2914a'
down_revision = 'db972b098339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filter_name', 'filter_name_description',
               existing_type=sa.VARCHAR(),
               comment='Description of the filter',
               existing_comment='Descriptino of the filter',
               existing_nullable=True)
    op.create_unique_constraint(None, 'filter_name', ['filter_name'])
    op.create_foreign_key(None, 'fluxstd', 'filter_name', ['filter_j'], ['filter_name'])
    op.create_foreign_key(None, 'fluxstd', 'filter_name', ['filter_z'], ['filter_name'])
    op.create_foreign_key(None, 'fluxstd', 'filter_name', ['filter_g'], ['filter_name'])
    op.create_foreign_key(None, 'fluxstd', 'filter_name', ['filter_r'], ['filter_name'])
    op.create_foreign_key(None, 'fluxstd', 'filter_name', ['filter_y'], ['filter_name'])
    op.create_foreign_key(None, 'fluxstd', 'filter_name', ['filter_i'], ['filter_name'])
    op.create_foreign_key(None, 'target', 'filter_name', ['filter_j'], ['filter_name'])
    op.create_foreign_key(None, 'target', 'filter_name', ['filter_z'], ['filter_name'])
    op.create_foreign_key(None, 'target', 'filter_name', ['filter_y'], ['filter_name'])
    op.create_foreign_key(None, 'target', 'filter_name', ['filter_i'], ['filter_name'])
    op.create_foreign_key(None, 'target', 'filter_name', ['filter_g'], ['filter_name'])
    op.create_foreign_key(None, 'target', 'filter_name', ['filter_r'], ['filter_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'target', type_='foreignkey')
    op.drop_constraint(None, 'target', type_='foreignkey')
    op.drop_constraint(None, 'target', type_='foreignkey')
    op.drop_constraint(None, 'target', type_='foreignkey')
    op.drop_constraint(None, 'target', type_='foreignkey')
    op.drop_constraint(None, 'target', type_='foreignkey')
    op.drop_constraint(None, 'fluxstd', type_='foreignkey')
    op.drop_constraint(None, 'fluxstd', type_='foreignkey')
    op.drop_constraint(None, 'fluxstd', type_='foreignkey')
    op.drop_constraint(None, 'fluxstd', type_='foreignkey')
    op.drop_constraint(None, 'fluxstd', type_='foreignkey')
    op.drop_constraint(None, 'fluxstd', type_='foreignkey')
    op.drop_constraint(None, 'filter_name', type_='unique')
    op.alter_column('filter_name', 'filter_name_description',
               existing_type=sa.VARCHAR(),
               comment='Descriptino of the filter',
               existing_comment='Description of the filter',
               existing_nullable=True)
    # ### end Alembic commands ###
