"""Add nullable=False for some columns

Revision ID: c5f125bd0b9b
Revises: d34d4aa2914a
Create Date: 2022-12-07 14:10:54.033977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5f125bd0b9b'
down_revision = 'd34d4aa2914a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fluxstd', 'obj_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='Gaia EDR3 sourceid')
    op.alter_column('fluxstd', 'ra',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='RA (ICRS, degree)')
    op.alter_column('fluxstd', 'dec',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='Dec (ICRS, degree)')
    op.alter_column('fluxstd', 'input_catalog_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='input_catalog_id from the input_catalog table')
    op.alter_column('fluxstd', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Version string of the F-star selection')
    op.alter_column('sky', 'obj_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='Object ID in the sky catalog')
    op.alter_column('sky', 'ra',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='RA (ICRS, degree)')
    op.alter_column('sky', 'dec',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='Dec (ICRS, degree)')
    op.alter_column('sky', 'input_catalog_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='input_catalog_id from the input_catalog table')
    op.alter_column('sky', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Version string of the sky position')
    op.alter_column('target', 'obj_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='Object ID as specified by the observer at Phase 2 (can be same as the input_catalog_object_id)')
    op.alter_column('target', 'ra',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='RA (ICRS, degree)')
    op.alter_column('target', 'dec',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='Dec (ICRS, degree)')
    op.alter_column('target', 'target_type_id',
               existing_type=sa.INTEGER(),
               comment='target type ID (default: 1 = SCIENCE)',
               existing_nullable=True)
    op.alter_column('target', 'input_catalog_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Input catalog ID from the input_catalog table')
    op.alter_column('target_type', 'target_type_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Name for the target type.')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_type', 'target_type_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Name for the target type.')
    op.alter_column('target', 'input_catalog_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Input catalog ID from the input_catalog table')
    op.alter_column('target', 'target_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='target type ID (default: 1 = SCIENCE)',
               existing_nullable=True)
    op.alter_column('target', 'dec',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='Dec (ICRS, degree)')
    op.alter_column('target', 'ra',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='RA (ICRS, degree)')
    op.alter_column('target', 'obj_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='Object ID as specified by the observer at Phase 2 (can be same as the input_catalog_object_id)')
    op.alter_column('sky', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Version string of the sky position')
    op.alter_column('sky', 'input_catalog_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='input_catalog_id from the input_catalog table')
    op.alter_column('sky', 'dec',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='Dec (ICRS, degree)')
    op.alter_column('sky', 'ra',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='RA (ICRS, degree)')
    op.alter_column('sky', 'obj_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='Object ID in the sky catalog')
    op.alter_column('fluxstd', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Version string of the F-star selection')
    op.alter_column('fluxstd', 'input_catalog_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='input_catalog_id from the input_catalog table')
    op.alter_column('fluxstd', 'dec',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='Dec (ICRS, degree)')
    op.alter_column('fluxstd', 'ra',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='RA (ICRS, degree)')
    op.alter_column('fluxstd', 'obj_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='Gaia EDR3 sourceid')
    # ### end Alembic commands ###
