"""Make nullable=False for ob_code column.

Revision ID: 9ef97473b712
Revises: 85c7fd1caf42
Create Date: 2022-12-06 19:04:48.390219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef97473b712'
down_revision = '85c7fd1caf42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target', 'ob_code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Identifer for a combination of a target, observing mode, and exposure time in a program.')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target', 'ob_code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Identifer for a combination of a target, observing mode, and exposure time in a program.')
    # ### end Alembic commands ###
