"""Test q3c indexes

Revision ID: 099e9069f2b7
Revises: c987ab91b094
Create Date: 2023-05-05 18:16:44.225953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099e9069f2b7'
down_revision = 'c987ab91b094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
