"""Add columns of stellar parameters (teff and logg + confidence intervals) in the fluxstd table

Revision ID: 8ac6065d2225
Revises: 10e6d0a4610a
Create Date: 2023-04-20 16:38:04.417493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac6065d2225'
down_revision = '10e6d0a4610a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fluxstd', sa.Column('teff_brutus', sa.Float(), nullable=True, comment='Effective temperature from Brutus code [K]'))
    op.add_column('fluxstd', sa.Column('teff_brutus_low', sa.Float(), nullable=True, comment='Lower confidence level (16%) of effective temperature from Brutus code [K]'))
    op.add_column('fluxstd', sa.Column('teff_brutus_high', sa.Float(), nullable=True, comment='Upper confidence level (84%) of effective temperature from Brutus code [K]'))
    op.add_column('fluxstd', sa.Column('logg_brutus', sa.Float(), nullable=True, comment='Surface gravity from Brutus code [log cgs]'))
    op.add_column('fluxstd', sa.Column('logg_brutus_low', sa.Float(), nullable=True, comment='Lower confidence level (16%) of surface gravity from Brutus code [log cgs]'))
    op.add_column('fluxstd', sa.Column('logg_brutus_high', sa.Float(), nullable=True, comment='Upper confidence level (84%) of surface gravity from Brutus code [log cgs]'))
    # op.drop_index('fluxstd_q3c_ang2ipix_idx', table_name='fluxstd')
    # op.drop_index('sky_q3c_ang2ipix_idx', table_name='sky')
    # op.drop_index('target_q3c_ang2ipix_idx', table_name='target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('target_q3c_ang2ipix_idx', 'target', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # op.create_index('sky_q3c_ang2ipix_idx', 'sky', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # op.create_index('fluxstd_q3c_ang2ipix_idx', 'fluxstd', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    op.drop_column('fluxstd', 'logg_brutus_high')
    op.drop_column('fluxstd', 'logg_brutus_low')
    op.drop_column('fluxstd', 'logg_brutus')
    op.drop_column('fluxstd', 'teff_brutus_high')
    op.drop_column('fluxstd', 'teff_brutus_low')
    op.drop_column('fluxstd', 'teff_brutus')
    # ### end Alembic commands ###
