"""Add an index to version in fluxstd

Revision ID: 6aec47e0f339
Revises: 8ac6065d2225
Create Date: 2023-04-21 09:13:40.822777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aec47e0f339'
down_revision = '8ac6065d2225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('fluxstd_q3c_ang2ipix_idx', table_name='fluxstd')
    op.create_index(op.f('ix_fluxstd_version'), 'fluxstd', ['version'], unique=False)
    # op.drop_index('sky_q3c_ang2ipix_idx', table_name='sky')
    # op.drop_index('target_q3c_ang2ipix_idx', table_name='target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('target_q3c_ang2ipix_idx', 'target', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # op.create_index('sky_q3c_ang2ipix_idx', 'sky', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    op.drop_index(op.f('ix_fluxstd_version'), table_name='fluxstd')
    # op.create_index('fluxstd_q3c_ang2ipix_idx', 'fluxstd', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # ### end Alembic commands ###
