"""Add upload_id to input_catalog table

Revision ID: 320fc1f7de3b
Revises: 71eba81781d9
Create Date: 2024-02-02 15:37:55.782110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320fc1f7de3b'
down_revision = '71eba81781d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_catalog', sa.Column('upload_id', sa.String(length=16), nullable=True, comment='A 8-bit hex string (16 characters) assigned at the submission of the target list (default: empty string)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_catalog', 'upload_id')
    # ### end Alembic commands ###
