"""autoincrement input_catalog_id

Revision ID: eeb9bd9b8d91
Revises: b010233c946e
Create Date: 2024-04-15 10:21:12.653189

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eeb9bd9b8d91"
down_revision: Union[str, None] = "b010233c946e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# generated by the help of Copilot.
def upgrade() -> None:
    # Start a transaction block
    op.execute("BEGIN;")

    # Drop the foreign key constraints in the other tables
    op.execute(
        """
        ALTER TABLE sky DROP CONSTRAINT sky_input_catalog_id_fkey;
        ALTER TABLE fluxstd DROP CONSTRAINT fluxstd_input_catalog_id_fkey;
        ALTER TABLE target DROP CONSTRAINT target_input_catalog_id_fkey;
        ALTER TABLE cluster DROP CONSTRAINT cluster_input_catalog_id_fkey;
        """
    )

    # Rename the existing input_catalog_id column to tmp_input_catalog_id
    op.execute(
        """
        ALTER TABLE input_catalog RENAME COLUMN input_catalog_id TO tmp_input_catalog_id;
        """
    )

    # Create a new input_catalog_id column with the Identity option
    op.execute(
        """
        ALTER TABLE input_catalog ADD COLUMN input_catalog_id INT GENERATED BY DEFAULT AS IDENTITY;
        """
    )

    # Set the starting value of the sequence associated with the input_catalog_id column to 10000
    op.execute(
        """
        ALTER SEQUENCE input_catalog_input_catalog_id_seq RESTART WITH 10000 MAXVALUE 89999;
        """
    )

    # Copy the values from tmp_input_catalog_id to input_catalog_id
    op.execute(
        """
        UPDATE input_catalog SET input_catalog_id = tmp_input_catalog_id;
        """
    )

    # Drop the primary key constraint on tmp_input_catalog_id and add a primary key constraint on input_catalog_id in a single step
    op.execute(
        """
        ALTER TABLE input_catalog
        DROP CONSTRAINT input_catalog_pkey,
        ADD PRIMARY KEY (input_catalog_id);
        """
    )

    # Delete the tmp_input_catalog_id column
    op.execute(
        """
        ALTER TABLE input_catalog DROP COLUMN tmp_input_catalog_id;
        """
    )

    # Add the foreign key constraints back to the other tables
    op.execute(
        """
        ALTER TABLE sky ADD CONSTRAINT sky_input_catalog_id_fkey FOREIGN KEY (input_catalog_id) REFERENCES input_catalog (input_catalog_id);
        ALTER TABLE fluxstd ADD CONSTRAINT fluxstd_input_catalog_id_fkey FOREIGN KEY (input_catalog_id) REFERENCES input_catalog (input_catalog_id);
        ALTER TABLE target ADD CONSTRAINT target_input_catalog_id_fkey FOREIGN KEY (input_catalog_id) REFERENCES input_catalog (input_catalog_id);
        ALTER TABLE cluster ADD CONSTRAINT cluster_input_catalog_id_fkey FOREIGN KEY (input_catalog_id) REFERENCES input_catalog (input_catalog_id);
        """
    )

    # Commit the transaction block
    op.execute("COMMIT;")


def downgrade() -> None:
    # Start a transaction block
    op.execute("BEGIN;")

    # Drop the foreign key constraints in the other tables
    op.execute(
        """
        ALTER TABLE sky DROP CONSTRAINT sky_input_catalog_id_fkey;
        ALTER TABLE fluxstd DROP CONSTRAINT fluxstd_input_catalog_id_fkey;
        ALTER TABLE target DROP CONSTRAINT target_input_catalog_id_fkey;
        ALTER TABLE cluster DROP CONSTRAINT cluster_input_catalog_id_fkey;
        """
    )

    # Rename the existing input_catalog_id column to tmp_input_catalog_id
    op.execute(
        """
        ALTER TABLE input_catalog RENAME COLUMN input_catalog_id TO tmp_input_catalog_id;
        """
    )

    # Create a new input_catalog_id column without the Identity option
    op.execute(
        """
        ALTER TABLE input_catalog ADD COLUMN input_catalog_id INT;
        """
    )

    # Copy the values from tmp_input_catalog_id to input_catalog_id
    op.execute(
        """
        UPDATE input_catalog SET input_catalog_id = tmp_input_catalog_id;
        """
    )

    # Drop the primary key constraint on tmp_input_catalog_id and add a primary key constraint on input_catalog_id in a single step
    op.execute(
        """
        ALTER TABLE input_catalog
        DROP CONSTRAINT input_catalog_pkey,
        ADD PRIMARY KEY (input_catalog_id);
        """
    )

    # Delete the tmp_input_catalog_id column
    op.execute(
        """
        ALTER TABLE input_catalog DROP COLUMN tmp_input_catalog_id;
        """
    )

    # Add the foreign key constraints back to the other tables
    op.execute(
        """
        ALTER TABLE sky ADD CONSTRAINT sky_input_catalog_id_fkey FOREIGN KEY (input_catalog_id) REFERENCES input_catalog (input_catalog_id);
        ALTER TABLE fluxstd ADD CONSTRAINT fluxstd_input_catalog_id_fkey FOREIGN KEY (input_catalog_id) REFERENCES input_catalog (input_catalog_id);
        ALTER TABLE target ADD CONSTRAINT target_input_catalog_id_fkey FOREIGN KEY (input_catalog_id) REFERENCES input_catalog (input_catalog_id);
        ALTER TABLE cluster ADD CONSTRAINT cluster_input_catalog_id_fkey FOREIGN KEY (input_catalog_id) REFERENCES input_catalog (input_catalog_id);
        """
    )

    # Commit the transaction block
    op.execute("COMMIT;")
