"""add unique constraint on the sky table

Revision ID: c636e8e2ecc0
Revises: 065b74905fb6
Create Date: 2024-04-17 10:09:59.291914

Note: 
Before upgrading the database, I run the following query to avoid the violation of the unique constaint:
```
UPDATE sky SET obj_id = sky_id WHERE version = '20220915';
```
This is already implemented in the integrated code when processing sky objects.

- [ ] production db
- [x] e2e db

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c636e8e2ecc0"
down_revision = "065b74905fb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "sky_obj_id_input_catalog_id_version_key",
        "sky",
        ["obj_id", "input_catalog_id", "version"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sky_obj_id_input_catalog_id_version_key", "sky", type_="unique")
    # ### end Alembic commands ###
