"""add indexes to fluxstd

Revision ID: 385b6cdf44f7
Revises: ae27ee4ad568
Create Date: 2025-12-16 18:28:55.673441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385b6cdf44f7'
down_revision = 'ae27ee4ad568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fluxstd_input_catalog_fluxstdid', 'fluxstd', ['input_catalog_id', 'fluxstd_id'], unique=False)
    op.create_index('ix_fluxstd_version_fluxstdid', 'fluxstd', ['version', 'fluxstd_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fluxstd_version_fluxstdid', table_name='fluxstd')
    op.drop_index('ix_fluxstd_input_catalog_fluxstdid', table_name='fluxstd')
    # ### end Alembic commands ###
