"""add index in obj_id, input_catalog_id, and proposal_id for target table 

Revision ID: 89865530fdf1
Revises: 3923581e4392
Create Date: 2025-08-01 20:26:38.686170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89865530fdf1'
down_revision = '3923581e4392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('target_obj_id_input_catalog_id_idx', 'target', ['obj_id', 'input_catalog_id'], unique=False)
    op.create_index('target_proposal_id_idx', 'target', ['proposal_id'], unique=False)
    op.create_index('target_proposal_id_obj_id_idx', 'target', ['proposal_id', 'obj_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('target_proposal_id_obj_id_idx', table_name='target')
    op.drop_index('target_proposal_id_idx', table_name='target')
    op.drop_index('target_obj_id_input_catalog_id_idx', table_name='target')
    # ### end Alembic commands ###
