"""add gc_neighbor and is_dense_region columns

Revision ID: a251bdccb11f
Revises: 385b6cdf44f7
Create Date: 2026-01-29 17:28:38.712851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a251bdccb11f'
down_revision = '385b6cdf44f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fluxstd', sa.Column('is_gc_neighbor', sa.Boolean(), nullable=True, comment='Flag for globular cluster neighbor'))
    op.add_column('fluxstd', sa.Column('is_dense_region', sa.Boolean(), nullable=True, comment='Flag for dense stellar region'))
    op.alter_column('fluxstd', 'obj_id',
               existing_type=sa.BIGINT(),
               comment='source_id (e.g., Gaia EDR3, DR3, etc.)',
               existing_comment='Gaia EDR3 sourceid',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fluxstd', 'obj_id',
               existing_type=sa.BIGINT(),
               comment='Gaia EDR3 sourceid',
               existing_comment='source_id (e.g., Gaia EDR3, DR3, etc.)',
               existing_nullable=False)
    op.drop_column('fluxstd', 'is_dense_region')
    op.drop_column('fluxstd', 'is_gc_neighbor')
    # ### end Alembic commands ###
